export const actionTypes = {
    SET_MOVIES : "SET_MOVIES",
    SET_SELECTED_MOVIE : "SET_SELECTED_MOVIE",
    REMOVE_SELECTED_MOVIE : "REMOVE_SELECTED_MOVIE",
    SET_MOVIE_GENRES : "SET_MOVIE_GENRES"
}