
//Action Types

export const actionTypes = {
    SET_MOVIES : "SET_MOVIES",
    SET_SELECTED_MOVIE : "SET_SELECTED_MOVIE",
    REMOVE_SELECTED_MOVIE : "REMOVE_SELECTED_MOVIE",
    SET_MOVIE_GENRES : "SET_MOVIE_GENRES",
    SELECTED_GENRES: "SELECTED_GENRES",
    CLEAR_SELECTED_GENRE: "REMOVE_SELECTED_GENRE",
}